### ISSUE TITLE
数据的插入好慢啊0.0

### ISSUE THREAD

**Issue by xuke007008** [gaojunquan/JQFMDB#1]

**Comment by gaojunquan** [comment]
提高效率需要用事务,需要把操作放在事务的block中,方法为:- (void)jq_inTransaction:(void(^)(BOOL *rollback))block;

至于为什么会慢,为何需要用事务:
假如北京的一家A工厂接了上海一家B公司的500件产品的订单，思考一下：A工厂是生产完一件立即就送到B公司还是将500件产品全部生产完成后再送往B公司？答案肯定是后者，因为前者浪费了大量的时间、人力物力花费在往返于北京和上海之间。同样这个道理也能用在我们的数据库操作上。

**Comment by xuke007008** [comment]
恩恩，没有注意到这个接口，非常感谢！！！

**Comment by gaojunquan** [comment]
客气! 为了大家和项目的考虑, 如果使用过程中出现问题或者需要新功能接口提供, 请提一个issue, 需求合理会马上更新, 我每天都会关注 !

**Comment by Geforceyu** [comment]
如何监听事务完成，比如我想要一些批量数据的插入完成以后，界面才跳转
