### ISSUE TITLE
添加表失败

### ISSUE THREAD

**Issue by woniuwuyu** [gaojunquan/JQFMDB#6]
我用您的类添加表总是失败DB Query: INSERT INTO yxtable ) values ()

**Comment by gaojunquan** [comment]
从结果上来看, 可以判断你的model中没有属性, 或者是你没有创建表就直接插入model

**Comment by woniuwuyu** [comment]
jq_createTable:(NSString *)tableName dicOrModel:(id)parameters
这个方法不是创建表 并添加值吗  表确实创建不成功

**Comment by gaojunquan** [comment]
运行Demo没有问题的话就是你操作的问题了
JQFMDB *db = [JQFMDB shareDatabase];
 [db jq_createTable:@"user" dicOrModel:[Person class]]; //保证Person有属性

这是用Person类创建一个名为user的表

**Comment by woniuwuyu** [comment]
我看了里面写的 ，我直接将一个模型做参数（模型有值） ，不是默认也会创建表，然后添加里面的键值吗，

**Comment by gaojunquan** [comment]
把你的代码贴上来

**Comment by woniuwuyu** [comment]
JQFMDB *db = [JQFMDB shareDatabase:Downloaded_DB path:DB_Path];
                [db jq_inDatabase:^{
                    BOOL issuc = [db jq_insertTable:@"backgroundImgs" dicOrModel:model];
                    YXLog(@"%d",issuc);
                }];

**Comment by gaojunquan** [comment]
之前已经讨论了, 你没有建表就开始插入数据

**Comment by woniuwuyu** [comment]
看到了我去 尴尬了谢谢 思密达
